blank_issues_enabled: false

contact_links:
  - name: Questions & Help
    url: https://github.com/divyansh375/rollouts-plugin-trafficrouter-contour/issues
    about: Ask a question or start a discussion about "rollouts-plugin-trafficrouter-contour"
